input_stream: "input"
output_stream: "output"

node {
    calculator : "LLMCalculator"
    input_stream : "PROMPT:input"
    output_stream: "TOKEN:output"
    node_options: {
        [type.googleapis.com/mediapipe.LLMCalculatorOptions] {
            tokenizer_model_path: "C:\\data\\llm\\openvino_tokenizer.xml"
            detokenizer_model_path: "C:\\data\\llm\\openvino_detokenizer.xml"
            model_path: "C:\\data\\llm\\openvino_model.xml"
        }
    }

}
