input_stream: "input"
output_stream: "output"

node {
    calculator : "LLMCalculator"
    input_stream : "PROMPT:input"
    # input_stream : "HISTORY:previous_conversation"
    output_stream: "TOKEN:output"
    # output_stream : "HISTORY:previous_conversation"

}
